
DECLARE

  NOMBRE PRODUCTS.PRODUCT_NAME%TYPE  ;
  ITERACION NUMBER(10):=1 ; 
  CANTIDAD_PRODUCTOS NUMBER(10);

BEGIN

SELECT COUNT(PRODUCT_NAME) INTO CANTIDAD_PRODUCTOS FROM PRODUCTS ; 

LOOP
  EXIT WHEN(ITERACION>CANTIDAD_PRODUCTOS) ; 
  SELECT PRODUCT_NAME into NOMBRE FROM PRODUCTS WHERE PRODUCT_ID= ITERACION ;  
  DBMS_OUTPUT.PUT_LINE('El nombre del producto es '||nombre) ;
  ITERACION:= ITERACION +1 ; 
END LOOP ; 
END  ; 




