SET SERVEROUTPUT ON ; 
DECLARE

iteracion number(10):=0 ; 

TYPE TABLA_CATEGORIAS IS TABLE OF CATEGORIES%ROWTYPE index by pls_integer;
DATOS_CATEGORIA TABLA_CATEGORIAS ; 


BEGIN 

SELECT CATEGORIES.CATEGORY_ID , CATEGORIES.CATEGORY_NAME BULK COLLECT INTO DATOS_CATEGORIA FROM CATEGORIES ; 

  DBMS_OUTPUT.PUT_LINE('La cantidad de registros que retorna la consulta es: '||SQL%ROWCOUNT) ; 


WHILE(ITERACION<SQL%ROWCOUNT) LOOP
  DBMS_OUTPUT.PUT_LINE('EL CODIGO DE LA CATEGORIA ES : ' || DATOS_CATEGORIA(ITERACION+1).CODIGO_CATEGORIA);
  DBMS_OUTPUT.PUT_LINE('EL NOMBE DE LA CATEGORIA ES : ' || DATOS_CATEGORIA(ITERACION+1).NOMBRE_CATEGORIA);
ITERACION := ITERACION+1; 
END LOOP ; 

END ; 
