CREATE SEQUENCE SQ_TABLA_CATEGORIAS START WITH 5 INCREMENT BY 1 ; 

INSERT INTO CATEGORIES VALUES (SQ_TABLA_CATEGORIAS.NEXTVAL,'BICICLETAS PROFESIONALES') ;  

DECLARE 
  VALOR_ACTUAL_SQ NUMBER ;
BEGIN
  VALOR_ACTUAL_SQ:= SQ_TABLA_CATEGORIAS.CURRVAL ; 
  DBMS_OUTPUT.PUT_LINE('El valor actual de la secuencia es: '||VALOR_ACTUAL_SQ) ; 
END ; 

SET SERVEROUTPUT ON ; 