DECLARE
  NOMBRE PRODUCTS.PRODUCT_NAME%TYPE ;
  FECHA DATE ; 
  CODIGO_ERROR NUMBER ; 
  MSJ_ERROR VARCHAR2(1000);
BEGIN
  FECHA:='HOLA MUNDO'  ; 
  SELECT PRODUCT_NAME INTO NOMBRE FROM PRODUCTS;

  DBMS_OUTPUT.PUT_LINE('El nombre del producto con ID 1 ES: '||NOMBRE) ; 
  
  EXCEPTION
    WHEN TOO_MANY_ROWS THEN 
    CODIGOERROR:=SQLCODE ; 
       DBMS_OUTPUT.PUT_LINE('SE RETORNAN MUCHOS REGISTROS EN LA SENTENCIA, CODIGO DE ERROR: '||SQLCODE) ; 
       DBMS_OUTPUT.PUT_LINE(SQLERRM);
    WHEN others then
    IF(SQLCODE=-1858) THEN
    DBMS_OUTPUT.PUT_LINE('SE ESTAN ASIGNANDO TIPOS DE DATOS INCORRECTOS');
    END IF ; 
    
    
    
  
END ;

