CREATE OR REPLACE TRIGGER TG_CATEGORIAS
AFTER INSERT ON CATEGORIES
FOR EACH ROW 

BEGIN
  INSERT INTO BITACORAS VALUES(SQ_BITACORAS.NEXTVAL,'Se realizo un insert en la tabla categorias y el
  dato nuevo en el ID es: '||:NEW.CATEGORY_ID ||'Y EL NOMBRE DE LA CATEGORIA ES '||:NEW.CATEGORY_NAME,
  SYSTIMESTAMP,USER,'OPERACION INSERT');  
  
  
  COMMIT ; 

END ; 


begin
INSERT INTO CATEGORIES (CATEGORY_NAME) VALUES ('Bicicletas Players');
commit ;
end ; 
