CREATE OR REPLACE TRIGGER TG_SQ_TABLA_CATEGORIAS
BEFORE INSERT ON CATEGORIES
FOR EACH ROW

DECLARE

BEGIN
  :NEW.CATEGORY_ID:=SQ_TABLA_CATEGORIAS.NEXTVAL; 
END ; 

DECLARE

BEGIN
insert into categories (CATEGORY_NAME)  values ('BICICLETAS HIBRIDAS') ; 
insert into categories (CATEGORY_NAME)  values ('BICICLETAS PLEGABLES') ; 

END ; 