DECLARE 
 TYPE ARREGLO IS TABLE OF VARCHAR2(100) INDEX BY PLS_INTEGER ; 
 DATOS ARREGLO ; 

BEGIN 
  DATOS(1):='Elemento 1';
  DATOS(2):='Elemento 2';
  DATOS(3):='Elemento 3';
  DATOS(4):='Elemento 4';
  
  
  FOR ITERACION IN 1..DATOS.COUNT LOOP 
    DBMS_OUTPUT.PUT_LINE(DATOS(ITERACION)) ; 
  END LOOP;
  
   DBMS_OUTPUT.PUT_LINE(DATOS.PRIOR(3)) ; 
   
   
   DATOS.DELETE(1) ; 


END  ;

SET SERVEROUTPUT  ON ; 