-- EXAMEN I 
-- ANDREA MICHELLE CALIX GONZALEZ 20171000581

--EJERCICIO 1
DECLARE
  ITERACION NUMBER(15):=0;
  
  TYPE FILA IS RECORD(
    DEPTO_ID DEPARTMENTS.DEPARTMENT_ID%TYPE,
    NOMBRE_DEPTO DEPARTMENTS.DEPARTMENT_NAME%TYPE,
    DIRECCION_EMPRESA LOCATIONS.STREET_ADDRESS%TYPE,
    CODIG_POSTAL LOCATIONS.POSTAL_CODE%TYPE
  );
  
  TYPE TBL_DEPTO_20171000581 IS TABLE OF FILA INDEX BY PLS_INTEGER;
  DATOS_DEPTO TBL_DEPTO_20171000581;
  

BEGIN
  
  SELECT DEPARTMENTS.DEPARTMENT_ID, DEPARTMENTS.DEPARTMENT_NAME, LOCATIONS.STREET_ADDRESS,
  LOCATIONS.POSTAL_CODE BULK COLLECT INTO DATOS_DEPTO FROM DEPARTMENTS INNER JOIN LOCATIONS ON DEPARTMENTS.LOCATION_ID=LOCATIONS.LOCATION_ID;
  
  WHILE (ITERACION<SQL%ROWCOUNT) LOOP

    DBMS_OUTPUT.PUT_LINE('EL ID DEL DEPTO ES: ' || DATOS_DEPTO(ITERACION+1).DEPTO_ID);
    DBMS_OUTPUT.PUT_LINE('EL NOMBRE DEL DEPTO ES: ' || DATOS_DEPTO(ITERACION+1).NOMBRE_DEPTO);
    DBMS_OUTPUT.PUT_LINE('LA DIRECCION: ' || DATOS_DEPTO(ITERACION+1).DIRECCION_EMPRESA);
    DBMS_OUTPUT.PUT_LINE('EL CODIGO POSTAL : ' || DATOS_DEPTO(ITERACION+1).CODIG_POSTAL);
    
    ITERACION:=ITERACION+1;
  END LOOP;
  
  DBMS_OUTPUT.PUT_LINE('LA CANTIDAD DE REGISTROS ES: ' || SQL%ROWCOUNT);

END;