
CREATE TABLE TBL_LOGS_20171000581(
 PK_COD_LOG NUMBER PRIMARY KEY,
 DESCRIPCION VARCHAR2(500),
 FECHA_HORA TIMESTAMP,
 USUARIO VARCHAR2(50),
 OPERACION VARCHAR2(20),
 TABLA_AFECTADA VARCHAR2(30)
);

CREATE SEQUENCE SQ_tbl_LOGS_20171000581
START WITH 1
INCREMENT BY 5;

--TRIGGER EN EMPLOYEES INSERT
CREATE OR REPLACE TRIGGER TBL_LOGS_20171000581
AFTER INSERT ON EMPLOYEES
FOR EACH ROW
DECLARE
 PRAGMA AUTONOMOUS_TRANSACTION;
BEGIN 
  INSERT INTO TBL_LOGS_20171000581 VALUES(SQ_tbl_LOGS_20171000581.NEXTVAL,'SE REALIZO UN INSERT EN LA TABLA EMPLEADOS Y EL DATO NUEVO
  EN EL ID ES: '||:NEW.EMPLOYEE_ID || 'Y EL NOMBRE ES: '||:NEW.FIRST_NAME ||' '||:NEW.LAST_NAME, SYSTIMESTAMP,USER,'OPERACION INSERT','EMPLOYEES');
  COMMIT;
  EXCEPTION
   WHEN OTHERS THEN 
      ROLLBACK;
END;

--TRIGGER EN DEPARTMENTS UPDATE
CREATE OR REPLACE TRIGGER TBL_DEPARTMENTS_20171000581
BEFORE UPDATE ON DEPARTMENTS
FOR EACH ROW
DECLARE
 PRAGMA AUTONOMOUS_TRANSACTION;
BEGIN 
  INSERT INTO TBL_LOGS_20171000581 VALUES(SQ_tbl_LOGS_20171000581.NEXTVAL,'SE REALIZO UN UPDATE EN LA TABLA DEPARTAMENTOS Y EL DATO NUEVO
  EN EL ID ES: '||:NEW.DEPARTMENT_ID || 'Y EL NOMBRE ES: '||:NEW.DEPARTMENT_NAME, SYSTIMESTAMP,USER,'OPERACION UPDATE','DEPARTMENTS');
  COMMIT;
  
  EXCEPTION
   WHEN OTHERS THEN 
      ROLLBACK;
END;

--TRIGGER EN JOB_HISTORY DELETE
CREATE OR REPLACE TRIGGER TBL_JOBHISTORY_20171000581
AFTER DELETE ON JOB_HISTORY
FOR EACH ROW
DECLARE
 PRAGMA AUTONOMOUS_TRANSACTION;
BEGIN 
  INSERT INTO TBL_LOGS_20171000581 VALUES(SQ_tbl_LOGS_20171000581.NEXTVAL,'SE REALIZO UN DELETE EN LA TABLA HISTORIAL DE TRABAJO
  EN EL ID ES: '||:NEW.JOB_ID,SYSTIMESTAMP,USER,'OPERACION DELETE','JOB_HISTORY');
  COMMIT;
  EXCEPTION
   WHEN OTHERS THEN 
      ROLLBACK;
END;



BEGIN
    --INSERT INTO EMPLOYEES VALUES(SQ_TABLAS_20171000581.NEXTVAL,'ROSA','GONZALEZ','@RG',NULL,SYSDATE,'MK_MAN',12000,null,null,90);
    --COMMIT;
   -- UPDATE DEPARTMENTS SET DEPARTMENT_NAME='Tecno' WHERE DEPARTMENT_ID=60;
    --COMMIT;
    DELETE FROM JOB_HISTORY WHERE JOB_ID='ST_CLERK';
    COMMIT;
END;



